plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/rake
    - gemfiles/**/*
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 20

Metrics/MethodLength:
  Max: 12
